export const EMAIL_LIST_REQUEST = "EMAIL_LIST_REQUEST";
export const EMAIL_LIST_SUCCESS = "EMAIL_LIST_SUCCESS";
export const EMAIL_LIST_FAIL = "EMAIL_LIST_FAIL";
export const EMAIL_LIST_RESET = "EMAIL_LIST_RESET";

export const EMAIL_BODY_REQUEST = "EMAIL_BODY_REQUEST";
export const EMAIL_BODY_SUCCESS = "EMAIL_BODY_SUCCESS";
export const EMAIL_BODY_FAIL = "EMAIL_BODY_FAIL";
export const EMAIL_BODY_RESET = "EMAIL_BODY_RESET";
